# Generated by Django 3.1.2 on 2021-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201222_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.IntegerField()),
                ('man', models.IntegerField()),
                ('pc_cahr', models.IntegerField()),
                ('white_board', models.IntegerField()),
                ('char_red', models.IntegerField()),
                ('char_yellow', models.IntegerField()),
                ('human_char', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='LabelInfo',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='videos/', verbose_name='動画ファイル'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
