# Generated by Django 3.1.2 on 2021-01-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210115_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label_info',
            old_name='pc_cahr',
            new_name='pc_char',
        ),
    ]
