# Generated by Django 3.1.2 on 2021-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210115_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label_info',
            name='char_red',
            field=models.IntegerField(blank=True, null=True, verbose_name='赤文字'),
        ),
        migrations.AlterField(
            model_name='label_info',
            name='char_yellow',
            field=models.IntegerField(blank=True, null=True, verbose_name='黄文字'),
        ),
        migrations.AlterField(
            model_name='label_info',
            name='human_char',
            field=models.IntegerField(blank=True, null=True, verbose_name='人'),
        ),
        migrations.AlterField(
            model_name='label_info',
            name='man',
            field=models.IntegerField(blank=True, null=True, verbose_name='男性'),
        ),
        migrations.AlterField(
            model_name='label_info',
            name='pc_char',
            field=models.IntegerField(blank=True, null=True, verbose_name='PC'),
        ),
        migrations.AlterField(
            model_name='label_info',
            name='sec',
            field=models.DateTimeField(blank=True, null=True, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='label_info',
            name='white_board',
            field=models.IntegerField(blank=True, null=True, verbose_name='白板'),
        ),
    ]
