# Generated by Django 3.1.2 on 2021-01-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210129_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label_info',
            name='sec',
            field=models.TimeField(blank=True, null=True, verbose_name='時間'),
        ),
    ]
